name: Backup PostgreSQL

on:
  schedule:
    - cron: '0 2 * * *'  # Executa diariamente às 02:00 UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configurar PostgreSQL
        env:
          PGHOST: ${{ secrets. }}       # Host da instância RDS
          PGUSER: ${{ secrets.RDS_USER }}       # Usuário do banco de dados
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }} # Senha do banco de dados
          PGDATABASE: ${{ secrets.RDS_DATABASE }} # Nome do banco de dados
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Executar backup
        env:RDS_HOST
          PGHOST: ${{ secrets.RDS_HOST }}
          PGUSER: ${{ secrets.RDS_USER }}
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
          PGDATABASE: ${{ secrets.RDS_DATABASE }}
          PGPORT: ${{ secrets.RDS_PORT }}
        run: |
          pg_dump -U $PGUSER -h $PGHOST $PGDATABASE -p $PGPORT > backup.sql

      - name: Salvar backup no repositório
        run: |
          git config --local user.email "rodrigo.sabinoti@gmail.com"
          git config --local user.name "rodsasilva
          git add backup.sql
          git commit -m "Backup do banco de dados em $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main  # Altere para a branch desejad
