name: Backup PostgreSQL

on:
  workflow_dispatch:  # A principio sera manual

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Instalar PostgreSQL client versão 16
        env:
          PGHOST: ${{ secrets.RDS_HOST }}
          PGUSER: ${{ secrets.RDS_USER }}
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
          PGDATABASE: ${{ secrets.RDS_DATABASE }}
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt-get install -y postgresql-client-16

      - name: Executar backup
        env:
          PGHOST: ${{ secrets.RDS_HOST }}
          PGUSER: ${{ secrets.RDS_USER }}
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
          PGDATABASE: ${{ secrets.RDS_DATABASE }}
          PGPORT: ${{ secrets.RDS_PORT }}
        run: |
          pg_dump -U $PGUSER -h $PGHOST -p $PGPORT $PGDATABASE -Fc -f backup_$(date +%Y-%m-%d).dump

      - name: Executa Criptografia
        env:
         PASSWORD: ${{ secrets.PASSWORD }}
        run: | #
          echo "$PASSWORD" | gpg -c --cipher-algo AES256 --batch --yes --passphrase-fd 0 backup_$(date +%Y-%m-%d).dump
<<<<<<< HEAD
=======

>>>>>>> 6437c996fc546e8cd9a2b0ce48d52890d4625e12

      - name: Salvar backup no repositório
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add backup_$(date +%Y-%m-%d).dump
          git commit -m "Backup do banco de dados em $(date +'%Y-%m-%d %H:%M:%S')"
          git push
